<div id="view_account">
  <form method="post" action="account.php">
    <h2>Update Information</h2>
    
    <label for="name">User Name</label>
    <input type="text" id="name" name="name" placeholder="User Name" required="" autofocus="">
    <br/>  
    <label for="email">E-mail</label>
    <input type="email" id="email" name="email" placeholder="E-mail" required="">
    <br/>
    <label for="password">Password</label>
    <input type="password" id="password" name="password" placeholder="Password" required="">
    <br/>

    <input type="submit" name="submit" value="Update">
  </form>
</div>





