<div class="login_form">
	<form  method="post" action="" role="form">
		<h2>Please sign in</h2>
		<label for="name">Username</label>
		<input type="text" name="name" placeholder="User Name" required="" autofocus="">
		<br/>
		<label for="name">Password</label>
		<input type="password" name="password" placeholder="Password" required="">
		<br/>
		<p><a href="find_password.php">Forget the password?</a>
		<br/>
		<input type="submit" name="submit"value="login">
	</form>
</div>