<div class="register_form">
  <h2>New User Register</h2>   
  <form method="post" action="register.php">
    <fieldset>
    <label for="name">User Name</label>
    <input type="text" id="name" name="name" placeholder="User Name" required="" autofocus="">
    <br/>  
    <label for="email">E-mail</label>
    <input type="email" id="email" name="email" placeholder="E-mail" required="">
    <br/>
    <label for="password">Password</label>
    <input type="password" id="password" name="password" placeholder="Password" required="">
    <br/>
    </fieldset>


    <input type="submit" name="submit" value="Submit">
    <input type="submit" name="submit" value="Reset">
  </form>
</div>





