<form method="post" action="">
  <h2>New User Register</h2>
 
  <label for="name">User Name</label>
  <input type="text" id="name" name="name" placeholder="User Name" required="" autofocus="">
  <br/>  
  <label for="email">E-mail</label>
  <input type="email" id="email" name="email" placeholder="E-mail" required="">
  <br/>
  <label for="password">Password</label>
  <input type="password" id="password" name="password" placeholder="Password" required="">
  <br/>
  <label for="repassword">Re-type Password</label>
  <input type="password" id="repassword" name="repassword" placeholder="Re-type Your Password" required="">
  <br/>  
  


  <input type="submit" value="Submit">
  <input type="submit" value="Reset">

</form>






